### PR TITLE
Set JULIA_NUM_THREADS=2 during installation

### PR DESCRIPTION
**Pull request by SaschaMann**
@davidanthoff and @DilumAluthge it would be great if one of you could check that this is actually a good idea :D

### CODE REVIEW

**Comment by davidanthoff** [comment]
What do we hope to gain from this?

My gut feeling is that we shouldn't do this, but instead if a specific package wants to test with multi threading, they should opt in to that.

**Comment by SaschaMann** [comment]
> What do we hope to gain from this?

Simplifying the workflow files and setting a default that matches the hardware of GitHub's runners. I don't know if there are any downsides to it, though.

**Comment by davidanthoff** [comment]
I think the major downside is that we would run the github actions with a non-default setting, which might lead to surprises. It is also worth mentioning that the whole threading API/stuff is still labeled as experimental in the docs and by the core group, as far as I can tell.

I think my preference would be to not do this right now. I would assume that Julia at some point changes the defaults around threading and will just use all available cores without a specific setting, and that seems to be the right moment to have the github actions also behave like that.

**Comment by SaschaMann** [comment]
Sounds reasonable. Thanks for reviewing :)

**Pull request closed without merging**
