### PR TITLE
Use .tar.gz files where available for faster win install

### PR DESCRIPTION
**Pull request by IanButterworth**
It currently takes almost a minute to install julia on windows via the .exe installer.
.zip takes ~42 seconds
.tar.gz takes ~12s :tada:

So let's use `.tar.gz` which is available all the way back to julia v1, and the exe if not

Closes https://github.com/julia-actions/setup-julia/issues/64

### CODE REVIEW

**Comment by IanButterworth** [comment]
Looks like it still takes ~42 seconds to unzip

**Comment by DilumAluthge** [comment]
Nice!

**Comment by KristofferC** [comment]
Nice indeed!

**Comment by IanButterworth** [comment]
I need a review approval to merge.

**Review by KristofferC — APPROVED** [review]

**Comment by KristofferC** [comment]
Ah yeah, that very useful feature....

**Comment by IanButterworth** [comment]
Seems it needs to come from someone in the org

**Review by ViralBShah — APPROVED** [review]

**Pull request merged**
