### PR TITLE
Bump the version number to `2.0.0` in `package.json` and `package-lock.json`

### PR DESCRIPTION
**Pull request by DilumAluthge**
Follow-up to https://github.com/julia-actions/setup-julia/pull/209

### CODE REVIEW

**Comment by IanButterworth** [comment]
Did you manually edit `package-lock.json`? It's machine generated by `npm build` and there was a diff when I ran that (that I just pushed).


FWIW, PR style nit.. I find keeping the PR title short and general to the concept "Bump version to 2.0.0" and the detail getting refined in the PR/commits to be a smoother approach with less noise for people following along.

**Review by ViralBShah — APPROVED** [review]

**Comment by IanButterworth** [comment]
I'm working on releasing this

**Comment by DilumAluthge** [comment]
I can run the release script when I get back to my computer, unless you beat me to it.

**Comment by DilumAluthge** [comment]
_Narrator: he did indeed beat him to it_

**Comment by DilumAluthge** [comment]
Thank you Ian!

**Comment by IanButterworth** [comment]
The script is a little bumpy for me. Notes:
- This line in the build script fails on MacOS and messes up the rest of the script https://github.com/julia-actions/bin/blob/31b4b500a3f419f3aed06ba1aa640bb41fdb835f/build-release.sh#L33 Error: `sed: 1: ".gitignore": invalid command code .`
- The script doesn't check you've got master checked out and up to date. I didn't at first, which resulted in a bad release branch being pushed with non-squashed commits. Then I couldn't fix it because delete and force push is disabled for release branches (I had to disable that momentarily for myself to fix it)

**Pull request merged**
