### PR TITLE
Add support for stable and lts Julia versions

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by SaschaMann** [comment]
Thanks for the PR!

---

The changes to `lib/setup-julia.js` confuse me. I'm wondering why it looks different than if I build it locally. Did you use `npm run build` to build it?

---

One thing to consider is that hardcoding these aliases will lock the Julia version to the action version. If a user specifies a specific version of the action or uses it from a local copy, they might not expect that `stable` doesn't always refer to the latest stable Julia version.

I can't think of a decent way to avoid this issue but perhaps we should add a warning to the README or the example. Do you have a better idea?

**Comment by davidanthoff** [comment]
I used the background TS compiler in VS Code, maybe it emits slightly different things than `npm run build`? I'll try and see what I get from `npm run build` in a moment.

Yeah, good point about the `stable` and `lts` labels... I guess I had been thinking that folks would use the `latest` branch of this action, but thinking about that, that seems pretty brittle. I think the best solution would be if the core julia downloads offered a `lts` and a `stable` download link, that was updated whenever a new version is released. This is something we should probably discuss across all the CI solutions: it would be great if travis, appveyor and all the others also supported the `lts` and `stable` label.

So maybe we'll wait with merging this here until that is sorted out.

**Comment by SaschaMann** [comment]
Other CI solutions have version like `1` pointing at whatever the latest stable release is or `1.1` pointing at the latest `1.1.x` release which is more or less the same as a stable label. However, other CI solutions don't give the user the same amount of control over what setup script is run, so they can update it more easily.

> I guess I had been thinking that folks would use the latest branch of this action, but thinking about that, that seems pretty brittle.

I might be overthinking this but I wouldn't be surprised if at least some people/orgs decide to use either a specific commit or even a copy of the action so that they can control precisely what is run for security reasons. GitHub even added an org setting to restrict where actions are loaded from. [Technically they don't have that control when they use Travis' build scripts either but at least in my mind there's a difference between trusting a company and some random repo on GitHub]

> I think the best solution would be if the core julia downloads offered a lts and a stable download link, that was updated whenever a new version is released.

That would be ideal.

Alternatively a (labeled) list of all available versions. This could be generated fairly easily but it's probably something that should live outside of this repo because otherwise it defeats the point of not having to trust a third party (this repo and everyone who has access to it). Perhaps it should be on the same server as the binaries.

> This is something we should probably discuss across all the CI solutions: it would be great if travis, appveyor and all the others also supported the lts and stable label.
>
> So maybe we'll wait with merging this here until that is sorted out.

Sounds good. I'd really like to hear other people's thoughts on this.

**Comment by SaschaMann** [comment]
I think I found a solution for a `stable` alias and other non-specific versions. 

If the version input matches a specific version (i.e. it looks like `1.1.1` or `1.2.0-rc3`), insert it directly into the download URL.

If it doesn't, fetch the list of tagged Julia versions from the GitHub API and use the maximum version that matches the criterion, e.g. `1.x` => latest available stable version where the major version equals 1. `stable` could just be the latest overall version that isn't a release candidate.

There's a brief period when a release might be tagged but binaries aren't available yet, which could lead to build failures. This seems rare enough that for now I'll just pretend this never happens and fix it if it ever becomes an actual problem.

An `lts` alias won't work with this, but I think manually updating the lts version from `1.0.x` to `1.?.x` every couple of years isn't a huge issue.

I'll create a new PR that adds this either today or tomorrow, so I'm gonna close this for now.

**Pull request closed without merging**
