### PR TITLE
1.9.6 and compat bump for node semver package

### PR DESCRIPTION
**Pull request by IanButterworth**
Seems the semver package had a moderate fix that's good to get out
```
ian@Ians-MBP setup-julia % npm install

changed 6 packages, and audited 438 packages in 1s

32 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
ian@Ians-MBP setup-julia % npm audit fix

changed 4 packages, and audited 438 packages in 628ms

32 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
ian@Ians-MBP setup-julia % 
```

### CODE REVIEW

**Comment by IanButterworth** [comment]
@DilumAluthge can you approve this if you're ok with the release being made

**Comment by DilumAluthge** [comment]
@IanButterworth I see 1.9.6 in "tags", but not in "releases".

**Comment by IanButterworth** [comment]
Yeah I'm testing it here https://github.com/JuliaLang/Pkg.jl/pull/3793 before pushing `v1` `v1.9` and making the release

**Comment by IanButterworth** [comment]
https://github.com/julia-actions/setup-julia/releases/tag/v1.9.6

**Pull request merged**
