### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by sunoru**
The vulnerabilities warnings and deprecation warnings are fixed.

### CODE REVIEW

**Comment by SaschaMann** [comment]
Doesn't seem to be as straightforward as the deprecation warning suggests: `src/setup-julia.ts(78,16): error TS2339: Property 'rmSync' does not exist on type 'typeof import("fs")'.`

**Comment by sunoru** [comment]
> Doesn't seem to be as straightforward as the deprecation warning suggests: `src/setup-julia.ts(78,16): error TS2339: Property 'rmSync' does not exist on type 'typeof import("fs")'.`

It is because the version of `@types/node` (v12) is too old but we are actually using node v16 on the ci

**Comment by sunoru** [comment]
I would like to turn this PR into bumping the dependency versions since many of them are too old and have vulnerabilities. Is that OK?

**Comment by sunoru** [comment]
And I don't understand why this was needed... https://github.com/julia-actions/setup-julia/pull/112

**Comment by SaschaMann** [comment]
> And I don't understand why this was needed... https://github.com/julia-actions/setup-julia/pull/112

Because without it, `npm install` didn't work and this was the suggested fix in the error message.

**Review by SaschaMann — APPROVED** [review]
Thanks for fixing all of this :)

**Comment by sunoru** [comment]
Nice, thank you for merging it!



> > And I don't understand why this was needed... #112
> 
> Because without it, `npm install` didn't work and this was the suggested fix in the error message.

Using `--legacy-peer-deps` would ignore a lot of dependency issues and I think it should be avoided 😂 (so I fixed them in this pr)

**Comment by sunoru** [comment]
BTW #119 can also be closed.

**Pull request merged**
