### PR TITLE
Change LTS 1.6 -> 1.10

### PR DESCRIPTION
**Pull request by IanButterworth**

### CODE REVIEW

**Comment by IanButterworth** [comment]
This needs tests updating but it's also pulling 1.10.2 not the latest patch for some reason

@KristofferC

**Comment by DilumAluthge** [comment]
Do we need to re-build `versions.json`? cc: @ararslan

**Comment by DilumAluthge** [comment]
> Do we need to re-build `versions.json`? cc: @ararslan

Just in case that's the issue, I have triggered a new re-build of `versions.json`: https://github.com/JuliaLang/VersionsJSONUtil.jl/actions/runs/11241255514

**Comment by ararslan** [comment]
I just checked the existing versions.json and it has 1.10.5

**Comment by DilumAluthge** [comment]
> but it's also pulling 1.10.2 not the latest patch for some reason

This one job ([log](https://github.com/julia-actions/setup-julia/actions/runs/11206747349/job/31147942720?pr=290)) gets 1.10.5:
```
julia version 1.10.5
```

**Comment by DilumAluthge** [comment]
Okay, so I checked the following CI logs:

1. test (lts, x64, ubuntu-latest) ([log](https://github.com/julia-actions/setup-julia/actions/runs/11206747349/job/31147942645?pr=290))
2. test (lts, x64, macOS-latest) ([log](https://github.com/julia-actions/setup-julia/actions/runs/11206747349/job/31147942720?pr=290))
3. test (lts, x64, windows-latest) ([log](https://github.com/julia-actions/setup-julia/actions/runs/11206747349/job/31147942797?pr=290))
4. test (lts, x86, ubuntu-latest) ([log](https://github.com/julia-actions/setup-julia/actions/runs/11206747349/job/31147942881?pr=290))
5. test (lts, x86, windows-latest) ([log](https://github.com/julia-actions/setup-julia/actions/runs/11206747349/job/31147942972?pr=290))

And for all five of the above jobs, the CI logs show `julia version 1.10.5` as the output for the `Run julia --version` step.

**Comment by KristofferC** [comment]
The npm tests use this as the input versions https://github.com/julia-actions/setup-julia/blob/83c1b1f3c9273c3f4b1f418f7436953644cf3b8a/__tests__/installer.test.ts#L29 (not `versions.json`). So that has to be updated as well.

**Review by DilumAluthge — DISMISSED** [review]

**Comment by DilumAluthge** [comment]
This has been released in v2.6.0.

The v2.6.0 tag has been created, and pushed, and the corresponding GitHub Release has been created: https://github.com/julia-actions/setup-julia/releases/tag/v2.6.0

The `v2` tag has been force-updated.

The `latest` tag has been force-updated.

**Pull request merged**
