### PR TITLE
Only show versioninfo() in debug mode

### PR DESCRIPTION
**Pull request by SaschaMann**

### CODE REVIEW

**Comment by davidanthoff** [comment]
Is there a downside to always showing it, and by default? I think it would be good if there was some version output always, that at least shows the version (no need for all the other stuff), would this remove that?

**Comment by SaschaMann** [comment]
> Is there a downside to always showing it, and by default?

It takes 1-2 seconds and it's not really necessary for workflows that only run in one version of Julia anyway. While it doesn't matter for each individual run, it can add up quite a bit.

It will show the output of `julia --version`, e.g. `julia version 1.0.5`, instead, but not the full `versioninfo()` anymore.

It might be a good idea to always show the full output for nightlies, though.

**Comment by davidanthoff** [comment]
Ah, ok, I didn't get that it would still show `julia --version`, agreed, that is totally enough!

**Comment by SaschaMann** [comment]
Thanks for reviewing :)

**Pull request merged**
